# app/crud/__init__.py - Re-export all public functions from sub-modules
from app.crud.project import (
    create_project,
    get_project,
    get_all_projects,
    list_projects_for_user,
    update_project,
    delete_project,
)
from app.crud.environment import (
    get_environments,
    get_environment,
    create_environment,
    update_environment,
    delete_environment,
    set_default_environment,
    ensure_default_environment,
    _sync_env_to_project,
)
from app.crud.module import (
    create_module,
    get_module,
    get_modules_for_project,
    get_module_tree,
    get_module_descendants,
    validate_module_parent,
    update_module,
    delete_module,
)
from app.crud.testcase import (
    create_test_step,
    get_steps_for_case,
    delete_steps_for_case,
    create_test_case,
    get_test_case,
    get_all_test_cases_for_project,
    get_all_test_cases_for_project_paginated,
    get_all_test_cases_for_module,
    get_all_test_cases_for_module_paginated,
    search_test_cases,
    update_test_case,
    update_test_case_is_init,
    get_init_test_cases,
    delete_test_case,
)
from app.crud.run import (
    create_test_run,
    update_test_run_status,
    create_run_log,
    create_run_batch,
    get_run_batch,
    list_run_batches,
    update_run_batch,
    delete_run_batch,
    update_batch_counters,
    _compute_batch_status,
    get_run_statistics,
    get_run_trends,
    list_recent_runs,
    get_run_detail_with_case,
    list_runs_with_case,
    get_batch_detail_with_related,
)
from app.crud.agent import (
    get_agent,
    get_agent_by_name,
    list_agents,
    create_agent,
    update_agent,
    delete_agent,
    list_agent_logs,
    update_agent_heartbeat,
)
from app.crud.gen import (
    list_gen_sessions,
    get_gen_session,
    create_gen_session,
    increment_imported_count,
    update_gen_session_status,
    persist_gen_session_results,
    delete_gen_session,
    list_gen_functional_points,
    list_gen_test_cases,
    get_gen_test_case,
    update_gen_test_case,
    delete_gen_test_case,
)
from app.crud.user import (
    list_users,
    get_user_by_username,
    get_user_by_id,
    get_users_by_ids,
    create_user,
    update_user_fields,
    unlock_user_if_expired,
    commit_user,
)
from app.crud.config import (
    get_ai_config,
    upsert_ai_config,
    list_prompt_templates,
    get_prompt_template_by_key,
    upsert_prompt_template,
    restore_prompt_template,
)
from app.crud.audit import (
    list_audit_logs,
)
from app.crud.schedule import (
    list_scheduled_tasks,
    get_scheduled_task,
    create_scheduled_task,
    update_scheduled_task,
    delete_scheduled_task,
    toggle_scheduled_task,
)

__all__ = [
    # project
    "get_db",
    "create_project",
    "get_project",
    "get_all_projects",
    "list_projects_for_user",
    "update_project",
    "delete_project",
    # environment
    "get_environments",
    "get_environment",
    "create_environment",
    "update_environment",
    "delete_environment",
    "set_default_environment",
    "ensure_default_environment",
    "_sync_env_to_project",
    # module
    "create_module",
    "get_module",
    "get_modules_for_project",
    "get_module_tree",
    "get_module_descendants",
    "validate_module_parent",
    "update_module",
    "delete_module",
    # testcase
    "create_test_step",
    "get_steps_for_case",
    "delete_steps_for_case",
    "create_test_case",
    "get_test_case",
    "get_all_test_cases_for_project",
    "get_all_test_cases_for_project_paginated",
    "get_all_test_cases_for_module",
    "get_all_test_cases_for_module_paginated",
    "search_test_cases",
    "update_test_case",
    "update_test_case_is_init",
    "get_init_test_cases",
    "delete_test_case",
    # run
    "create_test_run",
    "update_test_run_status",
    "create_run_log",
    "create_run_batch",
    "get_run_batch",
    "list_run_batches",
    "update_run_batch",
    "delete_run_batch",
    "update_batch_counters",
    "_compute_batch_status",
    "get_run_statistics",
    "get_run_trends",
    "list_recent_runs",
    "get_run_detail_with_case",
    "list_runs_with_case",
    "get_batch_detail_with_related",
    # agent
    "get_agent",
    "get_agent_by_name",
    "list_agents",
    "create_agent",
    "update_agent",
    "delete_agent",
    "list_agent_logs",
    "update_agent_heartbeat",
    # gen
    "list_gen_sessions",
    "get_gen_session",
    "create_gen_session",
    "increment_imported_count",
    "update_gen_session_status",
    "persist_gen_session_results",
    "delete_gen_session",
    "list_gen_functional_points",
    "list_gen_test_cases",
    "get_gen_test_case",
    "update_gen_test_case",
    "delete_gen_test_case",
    # user
    "list_users",
    "get_user_by_username",
    "get_user_by_id",
    "get_users_by_ids",
    "create_user",
    "update_user_fields",
    "unlock_user_if_expired",
    "commit_user",
    # config
    "get_ai_config",
    "upsert_ai_config",
    "list_prompt_templates",
    "get_prompt_template_by_key",
    "upsert_prompt_template",
    "restore_prompt_template",
    # audit
    "list_audit_logs",
    # schedule
    "list_scheduled_tasks",
    "get_scheduled_task",
    "create_scheduled_task",
    "update_scheduled_task",
    "delete_scheduled_task",
    "toggle_scheduled_task",
]  # noqa: E501
