# app/crud/__init__.py - Re-export all public functions from sub-modules
from app.crud.project import (
    get_db,
    create_project,
    get_project,
    get_all_projects,
    update_project,
    delete_project,
)
from app.crud.environment import (
    get_environments,
    get_environment,
    create_environment,
    update_environment,
    delete_environment,
    set_default_environment,
    ensure_default_environment,
    _sync_env_to_project,
)
from app.crud.module import (
    create_module,
    get_module,
    get_modules_for_project,
    get_module_tree,
    get_module_descendants,
    validate_module_parent,
    update_module,
    delete_module,
)
from app.crud.testcase import (
    create_test_step,
    get_steps_for_case,
    delete_steps_for_case,
    create_test_case,
    get_test_case,
    get_all_test_cases_for_project,
    get_all_test_cases_for_project_paginated,
    get_all_test_cases_for_module,
    get_all_test_cases_for_module_paginated,
    search_test_cases,
    update_test_case,
    update_test_case_is_init,
    get_init_test_cases,
    delete_test_case,
)
from app.crud.run import (
    create_test_run,
    update_test_run_status,
    create_run_log,
    create_run_batch,
    get_run_batch,
    list_run_batches,
    update_run_batch,
    update_batch_counters,
    _compute_batch_status,
)

__all__ = [
    # project
    "get_db",
    "create_project",
    "get_project",
    "get_all_projects",
    "update_project",
    "delete_project",
    # environment
    "get_environments",
    "get_environment",
    "create_environment",
    "update_environment",
    "delete_environment",
    "set_default_environment",
    "ensure_default_environment",
    "_sync_env_to_project",
    # module
    "create_module",
    "get_module",
    "get_modules_for_project",
    "get_module_tree",
    "get_module_descendants",
    "validate_module_parent",
    "update_module",
    "delete_module",
    # testcase
    "create_test_step",
    "get_steps_for_case",
    "delete_steps_for_case",
    "create_test_case",
    "get_test_case",
    "get_all_test_cases_for_project",
    "get_all_test_cases_for_project_paginated",
    "get_all_test_cases_for_module",
    "get_all_test_cases_for_module_paginated",
    "search_test_cases",
    "update_test_case",
    "update_test_case_is_init",
    "get_init_test_cases",
    "delete_test_case",
    # run
    "create_test_run",
    "update_test_run_status",
    "create_run_log",
    "create_run_batch",
    "get_run_batch",
    "list_run_batches",
    "update_run_batch",
    "update_batch_counters",
    "_compute_batch_status",
]