"""initial schema

Revision ID: 0044390972f6
Revises: 
Create Date: 2026-06-02 10:01:20.516854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0044390972f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parameterized_test_runs_id'), table_name='parameterized_test_runs')
    op.drop_table('parameterized_test_runs')
    op.drop_index(op.f('ix_test_case_data_bindings_id'), table_name='test_case_data_bindings')
    op.drop_table('test_case_data_bindings')
    op.drop_index(op.f('ix_test_case_versions_id'), table_name='test_case_versions')
    op.drop_table('test_case_versions')
    op.drop_index(op.f('ix_test_data_columns_id'), table_name='test_data_columns')
    op.drop_table('test_data_columns')
    op.drop_index(op.f('ix_test_data_rows_id'), table_name='test_data_rows')
    op.drop_table('test_data_rows')
    op.drop_index(op.f('ix_test_case_copies_id'), table_name='test_case_copies')
    op.drop_table('test_case_copies')
    op.drop_index(op.f('ix_test_data_sets_id'), table_name='test_data_sets')
    op.drop_table('test_data_sets')
    op.alter_column('scheduled_task_runs', 'task_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('scheduled_tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    op.alter_column('scheduled_tasks', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
    op.drop_constraint(None, 'scheduled_tasks', type_='foreignkey')
    op.drop_column('scheduled_tasks', 'next_run')
    op.drop_column('scheduled_tasks', 'last_run')
    op.drop_column('scheduled_tasks', 'project_id')
    op.drop_column('scheduled_tasks', 'fail_count')
    op.drop_column('scheduled_tasks', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_tasks', sa.Column('created_by', sa.VARCHAR(), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('fail_count', sa.INTEGER(), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('project_id', sa.INTEGER(), nullable=False))
    op.add_column('scheduled_tasks', sa.Column('last_run', sa.DATETIME(), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('next_run', sa.DATETIME(), nullable=True))
    op.create_foreign_key(None, 'scheduled_tasks', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
    op.alter_column('scheduled_tasks', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('scheduled_tasks', 'next_run_at')
    op.drop_column('scheduled_tasks', 'last_run_at')
    op.drop_column('scheduled_tasks', 'updated_at')
    op.alter_column('scheduled_task_runs', 'task_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('test_data_sets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('data_type', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_sets_id'), 'test_data_sets', ['id'], unique=False)
    op.create_table('test_case_copies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_case_id', sa.INTEGER(), nullable=False),
    sa.Column('target_case_id', sa.INTEGER(), nullable=False),
    sa.Column('copied_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('copy_type', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['source_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['target_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_copies_id'), 'test_case_copies', ['id'], unique=False)
    op.create_table('test_data_rows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.Column('row_index', sa.INTEGER(), nullable=False),
    sa.Column('row_data', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['test_data_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_rows_id'), 'test_data_rows', ['id'], unique=False)
    op.create_table('test_data_columns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.Column('column_name', sa.VARCHAR(), nullable=False),
    sa.Column('column_type', sa.VARCHAR(), nullable=True),
    sa.Column('column_order', sa.INTEGER(), nullable=False),
    sa.Column('default_value', sa.VARCHAR(), nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['test_data_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_columns_id'), 'test_data_columns', ['id'], unique=False)
    op.create_table('test_case_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('steps_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.Column('change_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_versions_id'), 'test_case_versions', ['id'], unique=False)
    op.create_table('test_case_data_bindings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.Column('binding_type', sa.VARCHAR(), nullable=True),
    sa.Column('specific_row_index', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['test_data_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_data_bindings_id'), 'test_case_data_bindings', ['id'], unique=False)
    op.create_table('parameterized_test_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('row_index', sa.INTEGER(), nullable=False),
    sa.Column('row_data', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['test_data_sets.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameterized_test_runs_id'), 'parameterized_test_runs', ['id'], unique=False)
    # ### end Alembic commands ###
