# core/llm_wrapper.py
"""
LLM wrapper for Playwright browser automation.

Replaces browser-use's LLM subclass with a standalone function that generates
structured Playwright tool calls from natural language step descriptions.

Architecture:
  NL step + DOM snapshot ──→ LLM (DashScope/Qwen) ──→ PlaywrightMCPToolCall (JSON)
"""

import asyncio
import json as _json
import logging
import os
import re
from typing import Any, Optional

import openai
from openai import AsyncOpenAI
from openai.types.chat import ChatCompletionContentPartTextParam
from pydantic import BaseModel, Field
from pydantic import ValidationError as PydanticValidationError

from app.security.encryption import decrypt_value

logger = logging.getLogger(__name__)

# ------------------------------------------------------------------
# Pydantic model for LLM output
# ------------------------------------------------------------------


class VerificationResult(BaseModel):
    """Result of verifying expected result against page state."""

    passed: bool = Field(..., description="Whether the expected result is met")
    reason: str = Field("", description="Brief explanation of the judgment")


class PlaywrightMCPToolCall(BaseModel):
    """A single browser action generated by the LLM from a NL step description."""

    action: str = Field(
        ...,
        description="One of: goto, click, fill, select, wait, screenshot, assert_text",
    )
    selector: Optional[str] = Field(
        None,
        description="CSS/text/XPath selector for the target element",
    )
    selector_type: str = Field(
        default='css',
        description="Selector type: css, text, xpath",
    )
    value: Optional[str] = Field(
        None,
        description="URL for goto, text for fill, option value for select",
    )
    timeout_ms: int = Field(
        default=30000,
        description="Timeout in milliseconds for this action",
    )
    thinking: Optional[str] = Field(
        None,
        description="LLM reasoning about why this action was chosen",
    )
    next_goal: Optional[str] = Field(
        None,
        description="What the agent plans to do after this step",
    )
    needs_verification: bool = Field(
        default=False,
        description="是否需要在执行完成后再次验证页面状态。"
        "设为 true 的场景：操作会影响页面状态（点击按钮后弹窗出现、提交后页面跳转、等待某元素出现等），"
        "需要 LLM 再次检查页面快照确认预期结果是否达成。"
        "设为 false 的场景：操作本身的效果就是预期结果（输入文字到输入框、勾选复选框、选择下拉项等），"
        "MCP 调用的返回就足以判断成功与否。",
    )


class VerificationCondition(BaseModel):
    """A single deterministic check condition parsed from natural-language expected_result.

    Level 1 of the tiered verification cascade — these conditions can be evaluated
    deterministically by the browser without needing further LLM calls.
    """

    check: str = Field(
        ...,
        description="检查类型: text_contains, text_matches, url_contains, url_matches, "
        "element_visible, element_count, page_title, js_expression",
    )
    target: str = Field(
        ...,
        description="检查目标值: 要搜索的字符串、正则表达式、选择器、计数值或 JS 表达式",
    )
    location: Optional[str] = Field(
        None,
        description="可选的位置提示: header, sidebar, main_content, right_sidebar, footer, modal 等",
    )


# ------------------------------------------------------------------
# LLM prompt for tool call generation
# ------------------------------------------------------------------

SYSTEM_PROMPT = """You are a precise browser automation agent using Playwright MCP.

INPUT you will receive:
1. A natural language step description (authoritative — the test case is already correct)
2. An accessibility snapshot of the current page (shows page structure with refs for each element)
3. The BASE URL for the target application (for navigation steps)
4. Optional EXPECTED RESULT (post-condition check hint — do NOT invent actions from it)

Your job: execute THIS step faithfully. Find the best matching element from the accessibility
snapshot and output a single action. Each element has a ref (e.g., e12, e45). Use refs as
the "selector" field. Prefer action="error" / action="wait" over guessing the wrong control.

--- SEMANTIC FIDELITY (highest priority — prevents wrong-but-plausible clicks) ---
1. Faithful execution: The step text is the source of truth. Do NOT reinterpret, "improve",
   or substitute a similar-looking control (e.g. 提交≠确定≠保存≠下一步; 查询≠搜索; 取消≠关闭).
2. Bracketed labels 【…】 / 「…」 are exact visible UI text. Match those strings first.
   Ignore control-type words outside brackets (下拉框/输入框/按钮/菜单/链接/弹窗).
3. One step = one primary action. Do not combine later steps, skip ahead, or finish the
   whole form early. Do not fill fields or click buttons the step never mentioned.
4. Do not invent values: only type/select text that appears in the step (or clearly implied
   by 「输入 xxx」). Never use remembered credentials or placeholder demos.
5. Ambiguity: if 2+ equally plausible targets exist, prefer wait for a clarifying text /
   expected keyword, or action="error" explaining the ambiguity — NEVER pick randomly.
6. Scope: stay on the current page/dialog unless the step explicitly says navigate / 打开 /
   进入 / 跳转. Do not close dialogs or switch menus unless the step asks.
7. Wait steps: action="wait" or "assert_text" with the text from the step/expected — do not
   click "something nearby" to kill time.
8. Thinking must quote the target label from the step and the chosen snapshot name/ref.

--- THINKING CHAIN (follow before every action) ---
1. 解析步骤意图 — Quote the exact target label/value from the step; list what NOT to do.
2. 分析当前页面状态 — What is visible? Any popups/dialogs blocking the page?
3. 确定目标元素位置 — Match using the progressive selector strategy below (unique match).
4. 选择最合适的工具 — Pick the action that matches element type and THIS step only.

ACTIONS available (maps to Playwright MCP tools):
- "goto": Navigate to a URL. selector=null, value=URL.
- "click": Click an element by its ref. selector=ref, value=null.
- "fill": Type text into an input field by ref. selector=ref, value=text.
- "select": Select dropdown option by ref. selector=ref, value=option value/text.
- "hover": Mouse hover over an element. selector=ref, value=null.
- "scroll": Scroll page by pixels or scroll element into view. selector=null (page), selector=ref (element), value=px count or "up"/"down".
- "press_key": Send keyboard key or shortcut. selector=null, value=key name (e.g. "Enter", "Tab", "Escape", "Control+A").
- "wait": Wait for text to appear. selector=null, value=text to wait for.
- "screenshot": Take a full-page screenshot. selector=null, value=filename.
- "assert_text": Wait for text to be visible. selector=null, value=text.
- "snapshot": Refresh page snapshot (no action). selector=null, value=null.

PROGRESSIVE SELECTOR MATCHING (try in this order):
1. Exact match — element text/name equals the step's target label exactly (prefer 【】/「」 text).
2. Partial match — element text/name CONTAINS the keyword from the step target (not control-type words).
3. aria-label match — if no text match exists, use the element's aria-label attribute.
4. Placeholder match — for input fields, match by placeholder attribute text.
5. If still ambiguous after the above → wait or error (see SEMANTIC FIDELITY #5).

DROPDOWN / SELECT (critical):
- Steps like "单位下拉框选择【汉东省院】" / "在【单位】下拉中选择【汉东省院】" mean:
  label = 单位 (field name), option = 汉东省院 (choice to pick).
- NEVER locate by the literal strings "下拉框" / "下拉" / "输入框" / "选择框" / "按钮" — these are control-type words from the step text, NOT page UI text.
- Prefer: combobox/listbox/select near accessible name or label text 「单位」; or option/menuitem named 「汉东省院」 if the list is already open.
- Native <select>: action="select", selector=ref of the select, value=option label/value.
- Custom dropdown (Ant Design etc.): click the combobox/selector to expand; if the option is already visible in the snapshot, click the option ref instead.
- For wait/assert_text: wait for the OPTION text (汉东省院) or field label (单位), never wait for "单位下拉框".

EDGE CASE HANDLING:
- Timeout: If element not found within 30s, retry once with a refreshed snapshot, then abort with action="error".
- Popup/Dialog: Only dismiss blocking popups when they prevent THIS step; prefer the dismiss control named in the step (关闭/取消/确定). Do not click 确定 on a confirm dialog unless the step says so.
- New browser tab: Clicks that open target=_blank / window.open are auto-switched by the runtime after click. On the next step, assume you are already on the newest tab; do not stay on the old page. If the snapshot still looks like the previous page, wait for key text on the new page.
- Stale Element: If an element reference becomes detached from the DOM, re-query the snapshot to find a fresh ref for the same element, then retry.
- Iframe: If the target element is inside an iframe, note the iframe boundary from the snapshot and switch context to that iframe first.

RULES:
- Use element refs from the snapshot (e.g., "e12") as selectors — do NOT invent CSS selectors or raw Chinese phrases as selectors.
- NEVER set selector/value to control-type words alone (下拉框/输入框/按钮). That causes Playwright getByText timeouts.
- Output ONLY the JSON object. No markdown fences, no explanation text.
- Always include "thinking" referencing the thinking chain stages and the exact labels matched.
- For text input fields, match by role="textbox" and accessible name, aria-label, or placeholder.
- For buttons, match by role="button" and accessible name or aria-label.
- For links, match by role="link" and text content.
- If no matching element found after exhausting all matching strategies, use action="error" with explanation in value.
- If navigation step, use action="goto" with the BASE URL as the value, or a full URL if the step explicitly specifies one.

OUTPUT SCHEMA (exact JSON):
{
  "action": "click",
  "selector": "e15",
  "value": null,
  "timeout_ms": 30000,
  "thinking": "Step wants to click 【提交】. Unique button ref=e15 name=提交. Not 确定/保存.",
  "next_goal": "Verify expected result for this step only"
}"""


# ------------------------------------------------------------------
# Configuration resolution
# ------------------------------------------------------------------


async def _load_db_config() -> dict:
    """Load the single AIConfig row from the database. Raises if absent or empty.

    The DB is seeded from config.json on first startup (see app/main.py).
    Uses async SQLAlchemy via AsyncSessionLocal.
    """
    from app.database import AsyncSessionLocal
    from sqlalchemy import select
    from app import db_models

    async with AsyncSessionLocal() as db:
        result = await db.execute(
            select(db_models.AIConfig).where(db_models.AIConfig.id == 1)
        )
        row = result.scalar_one_or_none()
        if not row:
            raise RuntimeError(
                "ai_configs table has no row (id=1). "
                "Configure AI via the Settings page (system admin) or PUT /api/config/ai."
            )
        return {
            'model': row.model,
            'api_key': decrypt_value(row.api_key),
            'api_base': row.api_base,
            'temperature': row.temperature,
        }


async def _resolve_config(
    explicit_key: str | None = None,
    explicit_base: str | None = None,
    explicit_model: str | None = None,
    agent_type: str | None = None,
) -> tuple[str, str, str]:
    """Resolve LLM config from the database (single source of truth).

    When `agent_type` is provided, try AgentDefinition's llm_config first;
    fall back to the global AIConfig if the lookup fails or returns no config.

    Explicit params override DB values. No environment, no Claude settings,
    no hardcoded defaults. Raises if DB row is missing — fail fast.
    """
    # 尝试 AgentDefinition 级别的 llm_config（通过 agent_resolver 缓存）
    if agent_type:
        try:
            from app.agent_resolver import resolve_agent_config
            from app.database import AsyncSessionLocal

            async with AsyncSessionLocal() as db:
                agent_cfg = await resolve_agent_config(db, agent_type)
            if agent_cfg:
                key = explicit_key or agent_cfg.get('api_key', '')
                base = explicit_base or agent_cfg.get('api_base', '')
                model = explicit_model or agent_cfg.get('model', '')
                if key:
                    return key, base or '', model or ''
        except Exception:
            logger.debug(
                "AgentDefinition lookup failed for agent_type=%s, "
                "falling back to global AIConfig",
                agent_type,
            )

    # 回退：全局 AIConfig
    cfg = await _load_db_config()

    missing = [k for k in ('api_key', 'api_base', 'model') if not cfg.get(k)]
    if missing and not any((explicit_key, explicit_base, explicit_model)):
        raise RuntimeError(
            f"AI config in database is missing required fields: {missing}. "
            f"Update via Settings page (system admin) or PUT /api/config/ai."
        )

    key = explicit_key or cfg.get('api_key', '')
    base = explicit_base or cfg.get('api_base', '')
    model = explicit_model or cfg.get('model', '')

    return key, base, model


# ------------------------------------------------------------------
# LLM tool call generation
# ------------------------------------------------------------------


async def create_openai_client(
    api_key: str | None = None,
    api_base: str | None = None,
    agent_type: str | None = None,
) -> AsyncOpenAI:
    """Create an OpenAI-compatible async client with resolved configuration."""
    key, base, _ = await _resolve_config(
        explicit_key=api_key,
        explicit_base=api_base,
        agent_type=agent_type,
    )
    if not key:
        raise ValueError(
            "No API key found. Set DASHSCOPE_API_KEY env var or configure "
            "config.json → ai.api_key or ~/.claude/settings.json"
        )
    return AsyncOpenAI(api_key=key, base_url=base)


async def generate_tool_call(
    step_description: str,
    dom_snapshot: str,
    *,
    expected_result: str | None = None,
    base_url: str | None = None,
    model: str | None = None,
    temperature: float = 0.1,
    client: AsyncOpenAI | None = None,
    system_prompt: str | None = None,
    agent_type: str | None = None,
    db: Any = None,
) -> PlaywrightMCPToolCall:
    """Generate a single PlaywrightMCPToolCall from a NL step description.

    Args:
        step_description: Natural language step, e.g. "点击登录按钮"
        dom_snapshot: Current page text content (visible text on the page)
        expected_result: Expected result after executing the step (optional)
        model: Override default model
        temperature: LLM temperature (lower = more deterministic)
        client: Pre-configured OpenAI client (created if not provided)

    Returns:
        Validated PlaywrightMCPToolCall

    Raises:
        ValueError: If the LLM output cannot be parsed or validated
    """
    if client is None:
        client = await create_openai_client()

    _, _, resolved_model = await _resolve_config(explicit_model=model)

    user_message = (
        f"STEP DESCRIPTION (authoritative — execute faithfully, do not reinterpret):\n"
        f"{step_description}\n\n"
        f"PAGE CONTENT (visible text / accessibility snapshot):\n"
        f"{dom_snapshot or '(empty page / no text available)'}\n\n"
        f"FIDELITY REMINDER: Match exact 【】/「」 labels; one primary action only; "
        f"if ambiguous prefer wait/error over a similar wrong control.\n\n"
    )
    if base_url:
        user_message += (
            "BASE URL (use only if this step requires navigation):\n"
            f"{base_url}\n\n"
        )
    if expected_result:
        user_message += (
            "EXPECTED RESULT (post-condition hint only — do not invent extra actions):\n"
            f"{expected_result}\n\n"
        )
    user_message += "Generate the browser action JSON for THIS step now."

    # 解析 system_prompt：显式参数 > DB 查找 > 硬编码常量
    resolved_system_prompt: str | None = system_prompt
    if resolved_system_prompt is None and agent_type and db is not None:
        try:
            from app.runtime_config import resolve_prompt_for_agent
            resolved_system_prompt = await resolve_prompt_for_agent(
                db, agent_type, "operation_translate",
            )
        except Exception:
            logger.debug(
                "DB prompt resolution failed for operation_translate "
                "(agent_type=%s), falling back to hardcoded SYSTEM_PROMPT",
                agent_type, exc_info=True,
            )
    if resolved_system_prompt is None:
        resolved_system_prompt = SYSTEM_PROMPT

    messages: list[dict] = [
        {'role': 'system', 'content': resolved_system_prompt},
        {'role': 'user', 'content': user_message},
    ]

    # Try up to 2 retries on invalid output
    last_error: Optional[str] = None
    for attempt in range(3):
        if attempt > 0 and last_error:
            messages.append({
                'role': 'user',
                'content': (
                    f"Previous response was invalid: {last_error}\n"
                    f"Please output ONLY the valid JSON object matching the schema."
                ),
            })

        try:
            response = await client.chat.completions.create(
                model=resolved_model,
                messages=messages,
                temperature=temperature,
                max_tokens=4096,
            )
        except Exception as exc:  # noqa: BLE001 - LLM 调用可能抛任意异常，retry 逻辑需吞掉所有
            logger.exception("LLM API call failed (attempt %s)", attempt + 1)
            if attempt >= 2:
                raise ValueError(f"LLM API call failed after 3 attempts: {exc}") from exc
            last_error = f"API error: {exc}"
            continue

        content = response.choices[0].message.content or ''
        content = content.strip()

        # Strip markdown fences if present
        content = re.sub(r'^```(?:json)?\s*', '', content)
        content = re.sub(r'\s*```$', '', content)

        # Try to repair common JSON issues
        try:
            parsed = _json.loads(content)
        except _json.JSONDecodeError:
            # Attempt repair: find first { and last }
            match = re.search(r'\{.*\}', content, re.DOTALL)
            if match:
                content = match.group(0)
            # Replace all single quotes with double quotes (handles LLMs that mix quotes)
            content = content.replace("'", '"')
            # Fix Python-style None/True/False
            content = re.sub(r':\s*None\b', ': null', content)
            content = re.sub(r':\s*True\b', ': true', content)
            content = re.sub(r':\s*False\b', ': false', content)
            # Fix trailing commas
            content = re.sub(r',\s*}', '}', content)
            content = re.sub(r',\s*]', ']', content)
            try:
                parsed = _json.loads(content)
            except _json.JSONDecodeError:
                # Last resort: try ast.literal_eval on original
                import ast
                try:
                    parsed = ast.literal_eval(content)
                except (ValueError, SyntaxError) as exc:
                    last_error = f"Invalid JSON: {exc}"
                    logger.warning("LLM output not valid JSON (attempt %s): %s", attempt + 1, content[:200])
                    continue

        try:
            tool_call = PlaywrightMCPToolCall.model_validate(parsed)
            return tool_call
        except PydanticValidationError as exc:
            last_error = f"Validation error: {exc}"
            logger.warning("LLM output failed Pydantic validation (attempt %s)", attempt + 1)
            continue

    raise ValueError(f"Failed to generate valid tool call after 3 attempts. Last error: {last_error}")


# ------------------------------------------------------------------
# Convenience: create LLM directly for test/debug
# ------------------------------------------------------------------

async def create_wrapped_llm(
    model: str | None = None,
    api_key: str | None = None,
    api_base: str | None = None,
    temperature: float = 0.1,
) -> AsyncOpenAI:
    """Convenience function returning a configured async OpenAI client.

    Keeps the old function name for backwards compatibility while
    returning an AsyncOpenAI client instead of a browser-use subclass.
    """
    return await create_openai_client(api_key=api_key, api_base=api_base)


# ------------------------------------------------------------------
# Expected result verification
# ------------------------------------------------------------------

VERIFY_PROMPT = """You are a precise test result verifier. Your job is to check whether the current page state matches the expected result using tiered verification.

INPUT:
1. STEP EXECUTED (optional): The action that was just performed
2. EXPECTED RESULT: What should be true after the step executes
3. PAGE CONTENT: Current accessibility snapshot of the page

--- THREE-TIER VERIFICATION ---

Level 1 — Exact Match: Text or element exactly equals the expected value.
  Examples: text "保存成功" appears verbatim, element ref=e25 is visible, URL contains "/dashboard".

Level 2 — Semantic Match: The meaning is equivalent even if wording differs.
  Examples: "保存成功" ≈ "Data saved successfully ✓", "登录完成" ≈ page shows user avatar + username.
  Use this when the intent is clearly satisfied but the exact wording varies.

Level 3 — Presence/Absence Check: Element exists or does not exist in the DOM.
  Examples: error toast exists, loading spinner is gone, modal dialog is not present.
  Use this for visibility/state checks that don't require specific text matching.

--- SPECIAL TOLERANCE RULES ---
- Timestamp/Dynamic Data: If the expected result references time, dates, IDs, or real-time data, check format/structure only — NOT the exact value. Example: "order ID shown" → verify any order ID exists, not a specific number.
- Input Success: If STEP EXECUTED describes an input/typing action and EXPECTED RESULT says it was successful (e.g. "输入成功"), check that the text appears in the input field — do NOT require a submission or confirmation message.

--- MULTI-ASSERTION RULE ---
If the expected result requires multiple checks (e.g. "URL changed to /dashboard AND success toast appears"), ALL checks must pass. If any single check fails, the entire verification returns passed=false.

--- CHINESE VERIFICATION EXAMPLES ---
Input: EXPECTED "页面包含'保存成功'文字" → Level 1: check exact text "保存成功" in snapshot.
Input: EXPECTED "弹出提示应该显示错误信息" → Level 2: check any error/warning message exists semantically.
Input: EXPECTED "登录后跳转到主页，右上角显示用户名" → Multi-assertion: both URL change AND username visible must pass.
Input: EXPECTED "订单创建成功，显示订单编号" → Level 3: order ID field exists (timestamp tolerance on value).

--- RULES ---
- If the snapshot is empty or unavailable, return passed=false with reason "Page snapshot is empty".
- Output ONLY the JSON object, no markdown fences.
- Always include specific evidence from the snapshot to justify your judgment.

OUTPUT FORMAT:
{
  "passed": true,
  "reason": "Page contains '保存成功' text at line 15 of snapshot",
  "evidence": "Snapshot line 15: '✓ 保存成功 — Data saved successfully'"
}

{
  "passed": false,
  "reason": "Expected success message not visible; snapshot shows only login page content",
  "evidence": "Snapshot lines 1-3 show login form, no success message found"
}"""


async def verify_expected_result(
    expected_result: str,
    dom_snapshot: str,
    *,
    step_description: str | None = None,
    model: str | None = None,
    temperature: float = 0.1,
    client: AsyncOpenAI | None = None,
    agent_type: str | None = None,
    db: Any = None,
) -> VerificationResult:
    """Verify if the current page state matches the expected result.

    Args:
        expected_result: What should be true after step execution
        dom_snapshot: Current page accessibility snapshot
        model: Override default model
        temperature: LLM temperature
        client: Pre-configured OpenAI client

    Returns:
        VerificationResult with passed=True/False and reason
    """
    if client is None:
        client = await create_openai_client()

    _, _, resolved_model = await _resolve_config(explicit_model=model)

    context = f"STEP EXECUTED:\n{step_description}\n\n" if step_description else ""
    user_message = (
        f"{context}"
        f"EXPECTED RESULT:\n{expected_result}\n\n"
        f"PAGE CONTENT (accessibility snapshot):\n"
        f"{dom_snapshot or '(empty page)'}\n\n"
        f"Verify if the expected result is met. Output JSON now."
    )

    # 解析 system_prompt：DB 查找 > 硬编码常量
    verify_prompt: str = VERIFY_PROMPT
    if agent_type and db is not None:
        try:
            from app.runtime_config import resolve_prompt_for_agent
            verify_prompt = await resolve_prompt_for_agent(
                db, agent_type, "verify_expected",
            )
        except Exception:
            logger.debug(
                "DB prompt resolution failed for verify_expected "
                "(agent_type=%s), falling back to hardcoded VERIFY_PROMPT",
                agent_type, exc_info=True,
            )

    messages: list[dict] = [
        {'role': 'system', 'content': verify_prompt},
        {'role': 'user', 'content': user_message},
    ]

    try:
        response = await client.chat.completions.create(
            model=resolved_model,
            messages=messages,
            temperature=temperature,
            max_tokens=512,
        )

        content = response.choices[0].message.content or ''
        content = content.strip()

        # Strip markdown fences
        content = re.sub(r'^```(?:json)?\s*', '', content)
        content = re.sub(r'\s*```$', '', content)

        # Try to parse
        try:
            parsed = _json.loads(content)
        except _json.JSONDecodeError:
            # Attempt repair
            match = re.search(r'\{.*\}', content, re.DOTALL)
            if match:
                content = match.group(0)
            content = content.replace("'", '"')
            content = re.sub(r':\s*None\b', ': null', content)
            content = re.sub(r':\s*True\b', ': true', content)
            content = re.sub(r':\s*False\b', ': false', content)
            try:
                parsed = _json.loads(content)
            except _json.JSONDecodeError as e:
                logger.warning("Verification LLM output not valid JSON: %s", content[:200])
                return VerificationResult(passed=False, reason=f"LLM output parse error: {e}")

        return VerificationResult.model_validate(parsed)

    except Exception as exc:  # noqa: BLE001 - 验证 LLM 调用：吞掉所有异常并返回 passed=False
        logger.exception("Verification LLM call failed")
        return VerificationResult(passed=False, reason=f"Verification failed: {exc}")


# ------------------------------------------------------------------
# Tiered verification: Level 1 — structured conditions from NL
# ------------------------------------------------------------------

VERIFY_CONDITIONS_PROMPT = """You are a test condition extractor. Your job is to translate a natural-language expected result description into a list of structured, deterministic check conditions that can be evaluated by a browser without further LLM calls.

INPUT:
- EXPECTED RESULT: A natural-language description of what should be true after a test step executes.

OUTPUT: A JSON array of condition objects, each with:
- "check": string — one of: text_contains, text_matches, url_contains, url_matches, element_visible, element_count, page_title, js_expression
- "target": string — the value to check against (text substring, regex pattern, CSS selector, expected count as string, or JS expression)
- "location": string (optional) — a hint about where on the page to look: header, sidebar, main_content, right_sidebar, footer, modal, dialog, dropdown, toast, breadcrumb, table, form, navigation

CHECK TYPE GUIDE:
- text_contains — page text contains the target string (substring match, case-insensitive)
- text_matches — page text matches the target regex pattern
- url_contains — current browser URL contains the target substring
- url_matches — current browser URL matches the target regex pattern
- element_visible — an element matching the target CSS selector is visible on the page
- element_count — count of elements matching target CSS selector equals (or matches) the expected count; format target as "selector|count" or "selector|>=count"
- page_title — the browser page title contains the target string
- js_expression — evaluate the target as a JavaScript expression in the browser context; truthy = pass

RULES:
- Break down compound expectations into multiple conditions (e.g. "should be on dashboard page showing user stats" → url_contains + text_contains)
- Use specific, searchable substrings for text_contains (not vague descriptions)
- Use "location" to scope the check when the expected result mentions a specific area (sidebar, header, modal, etc.)
- For element_visible, target should be a valid CSS selector (e.g. ".user-menu", "[data-testid='logout']")
- If the expected result cannot be decomposed into deterministic checks, return an empty array []
- Output ONLY the JSON array, no markdown fences, no explanation text

EXAMPLES:
Input: "页面跳转到仪表盘，右侧边栏显示 super admin"
Output: [{"check": "url_contains", "target": "/dashboard"}, {"check": "text_contains", "target": "super admin", "location": "right_sidebar"}]

Input: "弹出登录成功提示"
Output: [{"check": "text_contains", "target": "登录成功", "location": "toast"}]

Input: "商品列表中应该有 5 个商品"
Output: [{"check": "element_count", "target": ".product-card|5"}]

Input: "页面标题包含'用户管理'"
Output: [{"check": "page_title", "target": "用户管理"}]

Input: "结果显示在表格中"
Output: [{"check": "element_visible", "target": "table", "location": "main_content"}]

Input: "这是一个模糊的预期结果"
Output: []
"""


async def generate_verification_conditions(
    expected_result: str,
    *,
    client: AsyncOpenAI | None = None,
    model: str | None = None,
    temperature: float = 0.1,
) -> list[VerificationCondition]:
    """从自然语言预期结果生成结构化验证条件（层级 1）。

    层级验证级联的第一层：LLM 将自然语言 expected_result 翻译为
    结构化 JSON 条件列表，可由浏览器确定性评估，无需进一步 LLM 调用。

    Args:
        expected_result: 预期结果的自然语言描述
        client: 预配置的 OpenAI 客户端（未提供则自动创建）
        model: 覆盖默认模型
        temperature: LLM 温度参数

    Returns:
        list[VerificationCondition]: 验证条件列表；任何失败返回空列表（永不抛异常）
    """
    if not expected_result or not expected_result.strip():
        return []

    if client is None:
        try:
            client = await create_openai_client()
        except Exception as exc:  # noqa: BLE001 - 配置缺失时吞异常返回空列表
            logger.warning("Failed to create OpenAI client for verification conditions: %s", exc)
            return []

    try:
        _, _, resolved_model = await _resolve_config(explicit_model=model)
    except Exception as exc:  # noqa: BLE001 - 配置解析失败吞异常
        logger.warning("Failed to resolve config for verification conditions: %s", exc)
        return []

    user_message = (
        f"EXPECTED RESULT:\n{expected_result}\n\n"
        f"Translate this into structured verification conditions. Output JSON array now."
    )

    messages: list[dict] = [
        {'role': 'system', 'content': VERIFY_CONDITIONS_PROMPT},
        {'role': 'user', 'content': user_message},
    ]

    try:
        response = await client.chat.completions.create(
            model=resolved_model,
            messages=messages,
            temperature=temperature,
            max_tokens=1024,
        )
    except Exception as exc:  # noqa: BLE001 - LLM API 调用失败吞异常
        logger.exception("Verification conditions LLM call failed")
        return []

    content = response.choices[0].message.content or ''
    content = content.strip()

    # Strip markdown fences
    content = re.sub(r'^```(?:json)?\s*', '', content)
    content = re.sub(r'\s*```$', '', content)

    # Try to parse & repair JSON — same pattern as generate_tool_call()
    try:
        parsed = _json.loads(content)
    except _json.JSONDecodeError:
        # Attempt repair: find first [ and last ]
        match = re.search(r'\[.*]', content, re.DOTALL)
        if match:
            content = match.group(0)
        content = content.replace("'", '"')
        content = re.sub(r':\s*None\b', ': null', content)
        content = re.sub(r':\s*True\b', ': true', content)
        content = re.sub(r':\s*False\b', ': false', content)
        content = re.sub(r',\s*}', '}', content)
        content = re.sub(r',\s*]', ']', content)
        try:
            parsed = _json.loads(content)
        except _json.JSONDecodeError as e:
            logger.warning("Verification conditions LLM output not valid JSON: %s", content[:200])
            return []

    # parsed must be a list
    if not isinstance(parsed, list):
        logger.warning("Verification conditions output not a list: %s", type(parsed).__name__)
        return []

    conditions: list[VerificationCondition] = []
    for idx, item in enumerate(parsed):
        if not isinstance(item, dict):
            logger.warning("Verification condition item %d is not a dict, skipping", idx)
            continue
        try:
            conditions.append(VerificationCondition.model_validate(item))
        except PydanticValidationError as e:
            logger.warning("Verification condition item %d failed validation: %s", idx, e)

    return conditions
