# core/llm_wrapper.py
"""
LLM wrapper for Playwright browser automation.

Replaces browser-use's LLM subclass with a standalone function that generates
structured Playwright tool calls from natural language step descriptions.

Architecture:
  NL step + DOM snapshot ──→ LLM (DashScope/Qwen) ──→ PlaywrightMCPToolCall (JSON)
"""

import asyncio
import json as _json
import logging
import os
import re
from typing import Any, Optional

import openai
from openai import AsyncOpenAI
from openai.types.chat import ChatCompletionContentPartTextParam
from pydantic import BaseModel, Field
from pydantic import ValidationError as PydanticValidationError

from app.security.encryption import decrypt_value

logger = logging.getLogger(__name__)

# ------------------------------------------------------------------
# Pydantic model for LLM output
# ------------------------------------------------------------------


class VerificationResult(BaseModel):
    """Result of verifying expected result against page state."""

    passed: bool = Field(..., description="Whether the expected result is met")
    reason: str = Field("", description="Brief explanation of the judgment")


class PlaywrightMCPToolCall(BaseModel):
    """A single browser action generated by the LLM from a NL step description."""

    action: str = Field(
        ...,
        description="One of: goto, click, fill, select, wait, screenshot, assert_text",
    )
    selector: Optional[str] = Field(
        None,
        description="CSS/text/XPath selector for the target element",
    )
    selector_type: str = Field(
        default='css',
        description="Selector type: css, text, xpath",
    )
    value: Optional[str] = Field(
        None,
        description="URL for goto, text for fill, option value for select",
    )
    timeout_ms: int = Field(
        default=30000,
        description="Timeout in milliseconds for this action",
    )
    thinking: Optional[str] = Field(
        None,
        description="LLM reasoning about why this action was chosen",
    )
    next_goal: Optional[str] = Field(
        None,
        description="What the agent plans to do after this step",
    )
    needs_verification: bool = Field(
        default=False,
        description="是否需要在执行完成后再次验证页面状态。"
        "设为 true 的场景：操作会影响页面状态（点击按钮后弹窗出现、提交后页面跳转、等待某元素出现等），"
        "需要 LLM 再次检查页面快照确认预期结果是否达成。"
        "设为 false 的场景：操作本身的效果就是预期结果（输入文字到输入框、勾选复选框、选择下拉项等），"
        "MCP 调用的返回就足以判断成功与否。",
    )


class VerificationCondition(BaseModel):
    """A single deterministic check condition parsed from natural-language expected_result.

    Level 1 of the tiered verification cascade — these conditions can be evaluated
    deterministically by the browser without needing further LLM calls.
    """

    check: str = Field(
        ...,
        description="检查类型: text_contains, text_matches, url_contains, url_matches, "
        "element_visible, element_count, page_title, js_expression",
    )
    target: str = Field(
        ...,
        description="检查目标值: 要搜索的字符串、正则表达式、选择器、计数值或 JS 表达式",
    )
    location: Optional[str] = Field(
        None,
        description="可选的位置提示: header, sidebar, main_content, right_sidebar, footer, modal 等",
    )


# ------------------------------------------------------------------
# LLM prompt for tool call generation
# ------------------------------------------------------------------

SYSTEM_PROMPT = """You are a precise browser automation agent using Playwright MCP.

INPUT you will receive:
1. A natural language step description (what the user wants to do)
2. An accessibility snapshot of the current page (shows page structure with refs for each element)
3. The BASE URL for the target application (for navigation steps)

Your job: find the best matching element from the accessibility snapshot and output a single
action to accomplish the step. Each element in the snapshot has a ref (e.g., e12, e45).
Use these refs as the "selector" field to target elements precisely.

ACTIONS available (maps to Playwright MCP tools):
- "goto": Navigate to a URL. selector=null, value=URL.
- "click": Click an element by its ref. selector=ref, value=null.
- "fill": Type text into an input field by ref. selector=ref, value=text.
- "select": Select dropdown option by ref. selector=ref, value=option value/text.
- "wait": Wait for text to appear. selector=null, value=text to wait for.
- "screenshot": Take a full-page screenshot. selector=null, value=filename.
- "assert_text": Wait for text to be visible. selector=null, value=text.
- "snapshot": Refresh page snapshot (no action). selector=null, value=null.

RULES:
- Use element refs from the snapshot (e.g., "e12") as selectors — do NOT invent CSS selectors.
- Output ONLY the JSON object. No markdown fences, no explanation text.
- Always include "thinking" explaining why you chose this action and element.
- For text input fields, match by role="textbox" and accessible name.
- For buttons, match by role="button" and accessible name.
- For links, match by role="link" and text content.
- If no matching element found, use action="error" with explanation in value.
- If navigation step, use action="goto" with the BASE URL as the value, or a full URL if the step explicitly specifies one.

OUTPUT SCHEMA (exact JSON):
{
  "action": "click",
  "selector": "e15",
  "value": null,
  "timeout_ms": 30000,
  "thinking": "Step wants to click submit button. Found button ref=e15 with name 'Submit'.",
  "next_goal": "Verify login success message"
}"""


# ------------------------------------------------------------------
# Configuration resolution
# ------------------------------------------------------------------


async def _load_db_config() -> dict:
    """Load the single AIConfig row from the database. Raises if absent or empty.

    The DB is seeded from config.json on first startup (see app/main.py).
    Uses async SQLAlchemy via AsyncSessionLocal.
    """
    from app.database import AsyncSessionLocal
    from sqlalchemy import select
    from app import db_models

    async with AsyncSessionLocal() as db:
        result = await db.execute(
            select(db_models.AIConfig).where(db_models.AIConfig.id == 1)
        )
        row = result.scalar_one_or_none()
        if not row:
            raise RuntimeError(
                "ai_configs table has no row (id=1). "
                "Configure AI via the Settings page (system admin) or PUT /api/config/ai."
            )
        return {
            'model': row.model,
            'api_key': decrypt_value(row.api_key),
            'api_base': row.api_base,
            'temperature': row.temperature,
        }


async def _resolve_config(
    explicit_key: str | None = None,
    explicit_base: str | None = None,
    explicit_model: str | None = None,
) -> tuple[str, str, str]:
    """Resolve LLM config from the database (single source of truth).

    Explicit params override DB values. No environment, no Claude settings,
    no hardcoded defaults. Raises if DB row is missing — fail fast.
    """
    cfg = await _load_db_config()

    missing = [k for k in ('api_key', 'api_base', 'model') if not cfg.get(k)]
    if missing and not any((explicit_key, explicit_base, explicit_model)):
        raise RuntimeError(
            f"AI config in database is missing required fields: {missing}. "
            f"Update via Settings page (system admin) or PUT /api/config/ai."
        )

    key = explicit_key or cfg.get('api_key', '')
    base = explicit_base or cfg.get('api_base', '')
    model = explicit_model or cfg.get('model', '')

    return key, base, model


# ------------------------------------------------------------------
# LLM tool call generation
# ------------------------------------------------------------------


async def create_openai_client(
    api_key: str | None = None,
    api_base: str | None = None,
) -> AsyncOpenAI:
    """Create an OpenAI-compatible async client with resolved configuration."""
    key, base, _ = await _resolve_config(
        explicit_key=api_key,
        explicit_base=api_base,
    )
    if not key:
        raise ValueError(
            "No API key found. Set DASHSCOPE_API_KEY env var or configure "
            "config.json → ai.api_key or ~/.claude/settings.json"
        )
    return AsyncOpenAI(api_key=key, base_url=base)


async def generate_tool_call(
    step_description: str,
    dom_snapshot: str,
    *,
    expected_result: str | None = None,
    base_url: str | None = None,
    model: str | None = None,
    temperature: float = 0.1,
    client: AsyncOpenAI | None = None,
) -> PlaywrightMCPToolCall:
    """Generate a single PlaywrightMCPToolCall from a NL step description.

    Args:
        step_description: Natural language step, e.g. "点击登录按钮"
        dom_snapshot: Current page text content (visible text on the page)
        expected_result: Expected result after executing the step (optional)
        model: Override default model
        temperature: LLM temperature (lower = more deterministic)
        client: Pre-configured OpenAI client (created if not provided)

    Returns:
        Validated PlaywrightMCPToolCall

    Raises:
        ValueError: If the LLM output cannot be parsed or validated
    """
    if client is None:
        client = await create_openai_client()

    _, _, resolved_model = await _resolve_config(explicit_model=model)

    user_message = (
        f"STEP DESCRIPTION:\n"
        f"{step_description}\n\n"
        f"PAGE CONTENT (visible text):\n"
        f"{dom_snapshot or '(empty page / no text available)'}\n\n"
    )
    if base_url:
        user_message += f"BASE URL (use this for navigation if the step requires opening a page):\n{base_url}\n\n"
    if expected_result:
        user_message += (
            f"EXPECTED RESULT:\n"
            f"{expected_result}\n\n"
        )
    user_message += f"Generate the browser action JSON now."

    messages: list[dict] = [
        {'role': 'system', 'content': SYSTEM_PROMPT},
        {'role': 'user', 'content': user_message},
    ]

    # Try up to 2 retries on invalid output
    last_error: Optional[str] = None
    for attempt in range(3):
        if attempt > 0 and last_error:
            messages.append({
                'role': 'user',
                'content': (
                    f"Previous response was invalid: {last_error}\n"
                    f"Please output ONLY the valid JSON object matching the schema."
                ),
            })

        try:
            response = await client.chat.completions.create(
                model=resolved_model,
                messages=messages,
                temperature=temperature,
                max_tokens=4096,
            )
        except Exception as exc:  # noqa: BLE001 - LLM 调用可能抛任意异常，retry 逻辑需吞掉所有
            logger.exception("LLM API call failed (attempt %s)", attempt + 1)
            if attempt >= 2:
                raise ValueError(f"LLM API call failed after 3 attempts: {exc}") from exc
            last_error = f"API error: {exc}"
            continue

        content = response.choices[0].message.content or ''
        content = content.strip()

        # Strip markdown fences if present
        content = re.sub(r'^```(?:json)?\s*', '', content)
        content = re.sub(r'\s*```$', '', content)

        # Try to repair common JSON issues
        try:
            parsed = _json.loads(content)
        except _json.JSONDecodeError:
            # Attempt repair: find first { and last }
            match = re.search(r'\{.*\}', content, re.DOTALL)
            if match:
                content = match.group(0)
            # Replace all single quotes with double quotes (handles LLMs that mix quotes)
            content = content.replace("'", '"')
            # Fix Python-style None/True/False
            content = re.sub(r':\s*None\b', ': null', content)
            content = re.sub(r':\s*True\b', ': true', content)
            content = re.sub(r':\s*False\b', ': false', content)
            # Fix trailing commas
            content = re.sub(r',\s*}', '}', content)
            content = re.sub(r',\s*]', ']', content)
            try:
                parsed = _json.loads(content)
            except _json.JSONDecodeError:
                # Last resort: try ast.literal_eval on original
                import ast
                try:
                    parsed = ast.literal_eval(content)
                except (ValueError, SyntaxError) as exc:
                    last_error = f"Invalid JSON: {exc}"
                    logger.warning("LLM output not valid JSON (attempt %s): %s", attempt + 1, content[:200])
                    continue

        try:
            tool_call = PlaywrightMCPToolCall.model_validate(parsed)
            return tool_call
        except PydanticValidationError as exc:
            last_error = f"Validation error: {exc}"
            logger.warning("LLM output failed Pydantic validation (attempt %s)", attempt + 1)
            continue

    raise ValueError(f"Failed to generate valid tool call after 3 attempts. Last error: {last_error}")


# ------------------------------------------------------------------
# Convenience: create LLM directly for test/debug
# ------------------------------------------------------------------

async def create_wrapped_llm(
    model: str | None = None,
    api_key: str | None = None,
    api_base: str | None = None,
    temperature: float = 0.1,
) -> AsyncOpenAI:
    """Convenience function returning a configured async OpenAI client.

    Keeps the old function name for backwards compatibility while
    returning an AsyncOpenAI client instead of a browser-use subclass.
    """
    return await create_openai_client(api_key=api_key, api_base=api_base)


# ------------------------------------------------------------------
# Expected result verification
# ------------------------------------------------------------------

VERIFY_PROMPT = """You are a test result verifier. Your job is to check whether the current page state matches the expected result.

INPUT:
1. STEP EXECUTED (optional): The action that was just performed
2. EXPECTED RESULT: What should be true after the step executes
3. PAGE CONTENT: Current accessibility snapshot of the page

OUTPUT: A JSON object with:
- "passed": true if the expected result is clearly met, false otherwise
- "reason": brief explanation (1-2 sentences)

RULES:
- If STEP EXECUTED describes an input/typing action and EXPECTED RESULT says the input was successful (e.g. "输入成功", "输入完成"), check whether the text appears in the input field — do NOT require a submission or confirmation message
- If the expected result mentions specific text/elements, they must be visible in the snapshot
- If the snapshot is empty or unavailable, return passed=false
- Output ONLY the JSON object, no markdown fences

EXAMPLE OUTPUTS:
{"passed": true, "reason": "Search box contains 'berylliumman' as expected"}
{"passed": false, "reason": "Expected success message not visible on page"}
"""


async def verify_expected_result(
    expected_result: str,
    dom_snapshot: str,
    *,
    step_description: str | None = None,
    model: str | None = None,
    temperature: float = 0.1,
    client: AsyncOpenAI | None = None,
) -> VerificationResult:
    """Verify if the current page state matches the expected result.

    Args:
        expected_result: What should be true after step execution
        dom_snapshot: Current page accessibility snapshot
        model: Override default model
        temperature: LLM temperature
        client: Pre-configured OpenAI client

    Returns:
        VerificationResult with passed=True/False and reason
    """
    if client is None:
        client = await create_openai_client()

    _, _, resolved_model = await _resolve_config(explicit_model=model)

    context = f"STEP EXECUTED:\n{step_description}\n\n" if step_description else ""
    user_message = (
        f"{context}"
        f"EXPECTED RESULT:\n{expected_result}\n\n"
        f"PAGE CONTENT (accessibility snapshot):\n"
        f"{dom_snapshot or '(empty page)'}\n\n"
        f"Verify if the expected result is met. Output JSON now."
    )

    messages: list[dict] = [
        {'role': 'system', 'content': VERIFY_PROMPT},
        {'role': 'user', 'content': user_message},
    ]

    try:
        response = await client.chat.completions.create(
            model=resolved_model,
            messages=messages,
            temperature=temperature,
            max_tokens=512,
        )

        content = response.choices[0].message.content or ''
        content = content.strip()

        # Strip markdown fences
        content = re.sub(r'^```(?:json)?\s*', '', content)
        content = re.sub(r'\s*```$', '', content)

        # Try to parse
        try:
            parsed = _json.loads(content)
        except _json.JSONDecodeError:
            # Attempt repair
            match = re.search(r'\{.*\}', content, re.DOTALL)
            if match:
                content = match.group(0)
            content = content.replace("'", '"')
            content = re.sub(r':\s*None\b', ': null', content)
            content = re.sub(r':\s*True\b', ': true', content)
            content = re.sub(r':\s*False\b', ': false', content)
            try:
                parsed = _json.loads(content)
            except _json.JSONDecodeError as e:
                logger.warning("Verification LLM output not valid JSON: %s", content[:200])
                return VerificationResult(passed=False, reason=f"LLM output parse error: {e}")

        return VerificationResult.model_validate(parsed)

    except Exception as exc:  # noqa: BLE001 - 验证 LLM 调用：吞掉所有异常并返回 passed=False
        logger.exception("Verification LLM call failed")
        return VerificationResult(passed=False, reason=f"Verification failed: {exc}")


# ------------------------------------------------------------------
# Tiered verification: Level 1 — structured conditions from NL
# ------------------------------------------------------------------

VERIFY_CONDITIONS_PROMPT = """You are a test condition extractor. Your job is to translate a natural-language expected result description into a list of structured, deterministic check conditions that can be evaluated by a browser without further LLM calls.

INPUT:
- EXPECTED RESULT: A natural-language description of what should be true after a test step executes.

OUTPUT: A JSON array of condition objects, each with:
- "check": string — one of: text_contains, text_matches, url_contains, url_matches, element_visible, element_count, page_title, js_expression
- "target": string — the value to check against (text substring, regex pattern, CSS selector, expected count as string, or JS expression)
- "location": string (optional) — a hint about where on the page to look: header, sidebar, main_content, right_sidebar, footer, modal, dialog, dropdown, toast, breadcrumb, table, form, navigation

CHECK TYPE GUIDE:
- text_contains — page text contains the target string (substring match, case-insensitive)
- text_matches — page text matches the target regex pattern
- url_contains — current browser URL contains the target substring
- url_matches — current browser URL matches the target regex pattern
- element_visible — an element matching the target CSS selector is visible on the page
- element_count — count of elements matching target CSS selector equals (or matches) the expected count; format target as "selector|count" or "selector|>=count"
- page_title — the browser page title contains the target string
- js_expression — evaluate the target as a JavaScript expression in the browser context; truthy = pass

RULES:
- Break down compound expectations into multiple conditions (e.g. "should be on dashboard page showing user stats" → url_contains + text_contains)
- Use specific, searchable substrings for text_contains (not vague descriptions)
- Use "location" to scope the check when the expected result mentions a specific area (sidebar, header, modal, etc.)
- For element_visible, target should be a valid CSS selector (e.g. ".user-menu", "[data-testid='logout']")
- If the expected result cannot be decomposed into deterministic checks, return an empty array []
- Output ONLY the JSON array, no markdown fences, no explanation text

EXAMPLES:
Input: "页面跳转到仪表盘，右侧边栏显示 super admin"
Output: [{"check": "url_contains", "target": "/dashboard"}, {"check": "text_contains", "target": "super admin", "location": "right_sidebar"}]

Input: "弹出登录成功提示"
Output: [{"check": "text_contains", "target": "登录成功", "location": "toast"}]

Input: "商品列表中应该有 5 个商品"
Output: [{"check": "element_count", "target": ".product-card|5"}]

Input: "页面标题包含'用户管理'"
Output: [{"check": "page_title", "target": "用户管理"}]

Input: "结果显示在表格中"
Output: [{"check": "element_visible", "target": "table", "location": "main_content"}]

Input: "这是一个模糊的预期结果"
Output: []
"""


async def generate_verification_conditions(
    expected_result: str,
    *,
    client: AsyncOpenAI | None = None,
    model: str | None = None,
    temperature: float = 0.1,
) -> list[VerificationCondition]:
    """从自然语言预期结果生成结构化验证条件（层级 1）。

    层级验证级联的第一层：LLM 将自然语言 expected_result 翻译为
    结构化 JSON 条件列表，可由浏览器确定性评估，无需进一步 LLM 调用。

    Args:
        expected_result: 预期结果的自然语言描述
        client: 预配置的 OpenAI 客户端（未提供则自动创建）
        model: 覆盖默认模型
        temperature: LLM 温度参数

    Returns:
        list[VerificationCondition]: 验证条件列表；任何失败返回空列表（永不抛异常）
    """
    if not expected_result or not expected_result.strip():
        return []

    if client is None:
        try:
            client = await create_openai_client()
        except Exception as exc:  # noqa: BLE001 - 配置缺失时吞异常返回空列表
            logger.warning("Failed to create OpenAI client for verification conditions: %s", exc)
            return []

    try:
        _, _, resolved_model = await _resolve_config(explicit_model=model)
    except Exception as exc:  # noqa: BLE001 - 配置解析失败吞异常
        logger.warning("Failed to resolve config for verification conditions: %s", exc)
        return []

    user_message = (
        f"EXPECTED RESULT:\n{expected_result}\n\n"
        f"Translate this into structured verification conditions. Output JSON array now."
    )

    messages: list[dict] = [
        {'role': 'system', 'content': VERIFY_CONDITIONS_PROMPT},
        {'role': 'user', 'content': user_message},
    ]

    try:
        response = await client.chat.completions.create(
            model=resolved_model,
            messages=messages,
            temperature=temperature,
            max_tokens=1024,
        )
    except Exception as exc:  # noqa: BLE001 - LLM API 调用失败吞异常
        logger.exception("Verification conditions LLM call failed")
        return []

    content = response.choices[0].message.content or ''
    content = content.strip()

    # Strip markdown fences
    content = re.sub(r'^```(?:json)?\s*', '', content)
    content = re.sub(r'\s*```$', '', content)

    # Try to parse & repair JSON — same pattern as generate_tool_call()
    try:
        parsed = _json.loads(content)
    except _json.JSONDecodeError:
        # Attempt repair: find first [ and last ]
        match = re.search(r'\[.*]', content, re.DOTALL)
        if match:
            content = match.group(0)
        content = content.replace("'", '"')
        content = re.sub(r':\s*None\b', ': null', content)
        content = re.sub(r':\s*True\b', ': true', content)
        content = re.sub(r':\s*False\b', ': false', content)
        content = re.sub(r',\s*}', '}', content)
        content = re.sub(r',\s*]', ']', content)
        try:
            parsed = _json.loads(content)
        except _json.JSONDecodeError as e:
            logger.warning("Verification conditions LLM output not valid JSON: %s", content[:200])
            return []

    # parsed must be a list
    if not isinstance(parsed, list):
        logger.warning("Verification conditions output not a list: %s", type(parsed).__name__)
        return []

    conditions: list[VerificationCondition] = []
    for idx, item in enumerate(parsed):
        if not isinstance(item, dict):
            logger.warning("Verification condition item %d is not a dict, skipping", idx)
            continue
        try:
            conditions.append(VerificationCondition.model_validate(item))
        except PydanticValidationError as e:
            logger.warning("Verification condition item %d failed validation: %s", idx, e)

    return conditions
